### PR TITLE
Add curry compatibility

### PR DESCRIPTION
**Pull request by pr0vitamin**
Add compatibility for breaks where complex combinations of meat, spices, and herbs are consumed. Generally on a Friday.

### CODE REVIEW

**Comment by shweppsie** [comment]
I'm wondering if there's some scope for additional functionality here. I can't see a good reason the mandated Friday lunch curry can't be automatically called.

**Comment by pr0vitamin** [comment]
True, it does happen on a very regular basis.

**Comment by joestringer** [comment]
FWIW, I think it's against the fundamental ethos of teabreaking for it to be automated. If we start dabbling in that, it's a slippery slope.

**Comment by shweppsie** [comment]
Hmm, good point. Maybe we need google now integration to suggest when a regular event is coming up?

**Pull request merged**
